language: php
php:
    - 7.1

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester tests -s

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   stage: Code Standard Checker
            install:
                # Install Nette Code Checker
                - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
                # Install Nette Coding Standard
                - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress

            script:
                - php temp/code-checker/code-checker
                - php temp/coding-standard/ecs check src tests --config temp/coding-standard/coding-standard-php71.yml


sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
